---
- name: Launching an EC2 Instance
  local_action: ec2
                instance_type=t2.micro
                image=ami-9fa343e7
                region=us-west-2
                keypair=ec2key
                count=1
                group_id=sg-6f41c215
                wait=true
  register: ec2

- name: Add all instance public IPs to host group
  add_host: 
    hostname={{ item.public_ip }} 
    groups=ec2hosts 
    host_key_checking=False 
    ansible_ssh_user=ec2-user 
    ansible_ssh_port=22
    ansible_ssh_private_key_file=/home/centos/ansible_demo/cdproject/project/ec2key.pem

  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                delay=60
                timeout=320
                state=started
  with_items: "{{ ec2.instances }}"
